# nanoemoji UFSEmoji-Ext.toml
# Tool: nanoemoji
# Version: 0.15.8

family = "UFSEmoji-Ext"
output_file = "UFSEmoji-Ext.ttf"
color_format = "cff2_colr_1"
upem = 1024
width = 1275
ascender = 950
descender = -250
clipbox_quantization = 32

[axis.wght]
name = "Weight"
default = 400

[master.regular]
style_name = "Regular"
srcs = [
    "./emoji-svg/emoji_u1f6d9.svg",
    "./emoji-svg/emoji_u1fa8b.svg",
    "./emoji-svg/emoji_u1fa8c.svg",
    "./emoji-svg/emoji_u1fa8d.svg",
    "./emoji-svg/emoji_u1facc.svg",
    "./emoji-svg/emoji_u1fadd.svg",
    "./emoji-svg/emoji_u1faeb.svg",
    "./emoji-svg/emoji_u1faf9.svg",
    "./emoji-svg/emoji_u1fafa.svg",
]

[master.regular.position]
wght = 400